fix(bins): put a check for the existence of a requested service before acting on it

diff --git a/bin/svdrop b/bin/svdrop
--- a/bin/svdrop
+++ b/bin/svdrop
@@ -23,6 +23,9 @@ esac
 # set the default services dir
 if [ -z "$SVDIR" ]; then export SVDIR=$HOME/.sv; fi
 
+# make sure the service exists
+if [ ! -d "$SVDIR/$service" ]; then echo "Service '$service' not found in '$SVDIR'!"; exit 4; fi
+
 # stop the service
 if [[ $(sv s $service) != *"warning"* ]]; then "$(dirname $0)"/svstop $service; fi
 
diff --git a/bin/svstop b/bin/svstop
--- a/bin/svstop
+++ b/bin/svstop
@@ -22,6 +22,9 @@ esac
 # make sure we have a default for the services directory
 if [ -z "$SVDIR" ]; then export SVDIR="$HOME/.sv"; fi
 
+# make sure the service exists
+if [ ! -d "$SVDIR/$service" ]; then echo "Service '$service' not found in '$SVDIR'!"; exit 4; fi
+
 serviceDir="$SVDIR/$service"
 
 echo "Stopping service '$service' and removing supervise control"
diff --git a/bin/svwdown b/bin/svwdown
--- a/bin/svwdown
+++ b/bin/svwdown
@@ -27,6 +27,9 @@ if [ -z "$SVDIR" ]; then export SVDIR="$HOME/.sv"; fi
 
 serviceDir="$SVDIR/$name"
 
+# make sure the service exists
+if [ ! -d "$serviceDir" ]; then echo "Service '$name' not found in '$SVDIR'!"; exit 4; fi
+
 if [[ -e "$serviceDir/down" ]]; then echo "service already set to go down on startup"; exit 0; fi
 
 
diff --git a/bin/svwup b/bin/svwup
--- a/bin/svwup
+++ b/bin/svwup
@@ -27,6 +27,9 @@ if [ -z "$SVDIR" ]; then export SVDIR="$HOME/.sv"; fi
 
 serviceDir="$SVDIR/$name"
 
+# make sure the service exists
+if [ ! -d "$serviceDir" ]; then echo "Service '$name' not found in '$SVDIR'!"; exit 4; fi
+
 # remove service down file if it exists
 if [[ -e "$serviceDir/down" ]]; then rm -f "$serviceDir/down"; else echo "service already set to go up on startup"; exit 0; fi
 
