feat(svdrop): implement svdrop command

diff --git a/bin/svdrop b/bin/svdrop
--- a/bin/svdrop
+++ b/bin/svdrop
@@ -11,9 +11,29 @@ function printHelp {
 }
 
 case $# in
-		2) backup=$2;;&
+		2) backup=$2;&
 		1) service=$1;;
-		0 | *) printHelp; exit 2;;
+		0) printHelp; exit 2;;
 esac
 
+# echo service $service
+# echo backup $backup
+# exit 1
 
+# set the default services dir
+if [ -z "$SVDIR" ]; then SVDIR=$HOME/.sv; fi
+
+# stop the service
+"$(dirname $0)"/svstop $service
+
+if [ ! -z $backup ]; then
+		echo "backing up service to $backup ..."
+		mkdir -p "$backup"
+		cp -rf "$SVDIR/$service" "$backup"
+		if [[ $? == 0 ]]; then echo "service backup was successfull"; else echo "couldn't backup service!"; exit 3; fi
+fi
+
+echo "deleting service '$service'..."
+rm -rf "$SVDIR/$service"
+
+if [[ $? == 0 ]]; then echo "service was successfully removed"; fi
