fix(install & uninstall): correct installation and uninstallation errors
add error handles and correct the copy path

diff --git a/install b/install
--- a/install
+++ b/install
@@ -2,6 +2,6 @@
 # Emmanuel Mahuni (c) 2008 MIT
 #
 
-cp -fv bin/*.* $PREFIX/bin
+cp -fv bin/* $PREFIX/bin
 
-echo "installation complete!"
+if [ $? == 0 ]; then echo; echo "installation complete!"; else echo; echo "failed to install!"; fi
diff --git a/uninstall b/uninstall
--- a/uninstall
+++ b/uninstall
@@ -2,18 +2,7 @@
 # Emmanuel Mahuni (c) 2018 MIT
 #
 
-rf -fv $PREFIX/bin/svdrun
-rf -fv $PREFIX/bin/svdstop
-rf -fv $PREFIX/bin/svcreate
-rf -fv $PREFIX/bin/svact
-rf -fv $PREFIX/bin/svdeact
-rf -fv $PREFIX/bin/svstop
-rf -fv $PREFIX/bin/svrun
-rf -fv $PREFIX/bin/svstop
-rf -fv $PREFIX/bin/svdrop
-rf -fv $PREFIX/bin/svlist
-rf -fv $PREFIX/bin/svwup
-rf -fv $PREFIX/bin/svwdown
+rf -fv $PREFIX/bin/svdrun && rf -fv $PREFIX/bin/svdstop && rf -fv $PREFIX/bin/svcreate && rf -fv $PREFIX/bin/svact && rf -fv $PREFIX/bin/svdeact && rf -fv $PREFIX/bin/svstop && rf -fv $PREFIX/bin/svrun && rf -fv $PREFIX/bin/svstop && rf -fv $PREFIX/bin/svdrop && rf -fv $PREFIX/bin/svlist && rf -fv $PREFIX/bin/svwup && rf -fv $PREFIX/bin/svwdown
 
 
-echo "uninstallation complete!"
+if [ $? == 0 ]; then echo "uninstallation complete!"; else echo "failed to uninstall!"; fi
